### ISSUE TITLE
Optimization bundler for folder /dist (webpack.config.js)

### ISSUE THREAD

**Issue by KovaSs** [eternal-system/react-cli#22]

**Comment by KovaSs** [comment]
@VladKalachev  А то именно должно быть оптимизированно в webpack.config.js?

**Comment by VladKalachev** [comment]
@KovaSs нужно добавить модули для оптимизации бандла который нам генерит webpack
Например:
- optimize-css-assets-webpack-plugin
- terser-webpack-plugin

**Comment by KovaSs** [comment]
@VladKalachev  НУ по поводу минификации, в новом webpack который мы используем уже используется terser)
